#消息提示方式, 有actionbar(快捷栏),title(标题),subtitle(副标题),message(聊天栏)三种类型
#默认为actionbar
message_type: actionbar
message_keep_inventory_on: '&a死亡不掉落开启'
message_keep_inventory_off: '&c死亡不掉落关闭'
default_keep_inventory: true
message_command_reload: '&a插件已重载'